# Generated by Django 5.2.7 on 2025-10-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_owner', models.IntegerField()),
                ('campaign_poster', models.TextField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_objective', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_description', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_type', models.CharField(blank=True, max_length=20, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('content_deliverables', models.TextField(blank=True, null=True)),
                ('campaign_timeline', models.CharField(blank=True, max_length=20, null=True)),
                ('content_approval_required', models.BooleanField(default=False)),
                ('auto_match_micro_influencers', models.BooleanField(default=False)),
                ('target_audience', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords_and_hashtags', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
