# Generated by Django 5.2.7 on 2025-10-29 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
