# Generated by Django 5.2.8 on 2025-11-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_input', models.FileField(blank=True, null=True, upload_to='temp/')),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('hired_influencer_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('proposal_message', models.TextField(blank=True, null=True)),
                ('campaign_deliverables', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, null=True, to='campaign.files')),
            ],
        ),
    ]
