# Generated by Django 5.2.8 on 2025-11-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_files_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hire',
            name='is_accepted_by_influencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hire',
            name='is_completed_marked_by_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hire',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
