# Generated by Django 5.2.8 on 2025-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_hire_budget_hire_is_accepted_by_influencer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
