# Generated by Django 5.2.8 on 2025-12-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaign_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
