# Generated by Django 5.2.9 on 2025-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_hire_campaign_id_alter_campaign_campaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='campaign_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
