# Generated by Django 5.2.9 on 2025-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_alter_hire_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
