# Generated by Django 5.2.9 on 2025-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_campaign_campaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='budget_range',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_objective',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_timeline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='keywords_and_hashtags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='payment_preference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_audience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
