# Generated by Django 5.2.9 on 2025-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_alter_campaign_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='is_rejected_by_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
