# Generated by Django 5.2.9 on 2026-01-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_hire_is_rejected_by_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
