# Generated by Django 5.2.10 on 2026-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_hire_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='budgetNegotiable',
            field=models.BooleanField(default=False),
        ),
    ]
