# Generated by Django 5.2.7 on 2025-10-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('short_bio', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('tiktok_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('youtube_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('content_niches', models.TextField(blank=True, null=True)),
                ('audience_demographics', models.TextField(blank=True, null=True)),
                ('keyword_and_tags', models.TextField(blank=True, null=True)),
                ('content_formats', models.TextField(blank=True, null=True)),
                ('payment_preferences', models.TextField(blank=True, null=True)),
                ('rate_range_for_social_post', models.CharField(blank=True, max_length=20, null=True)),
                ('rate_range_for_youtube_video', models.CharField(blank=True, max_length=20, null=True)),
                ('rate_range_for_blog_post', models.CharField(blank=True, max_length=20, null=True)),
                ('rate_range_for_youtube_short', models.CharField(blank=True, max_length=20, null=True)),
                ('response_time', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brand_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.brandinfo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='influencer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.influencerinfo'),
        ),
    ]
