# Generated by Django 5.2.7 on 2025-10-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_brandinfo_influencerinfo_userprofile_signup_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='audience_demographic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='brand_tone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='business_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='choosen_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='keyword_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='short_bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='targeted_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
