# Generated by Django 5.2.7 on 2025-10-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_brandinfo_audience_demographic_brandinfo_brand_tone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='notifications_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='notifications_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_affiliate_marketing_percent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_instagram_reel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_instagram_story',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_live_stream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_podcast_mention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_repost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_tiktok_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_ugc_creation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_whatsapp_status_post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='stripe_connected',
            field=models.BooleanField(default=False),
        ),
    ]
