# Generated by Django 5.2.7 on 2025-10-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_influencerinfo_notifications_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signed_up_as',
            field=models.CharField(default='influencer', max_length=20),
        ),
    ]
