# Generated by Django 5.2.7 on 2025-10-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_brandinfo_designation_brandinfo_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
