# Generated by Django 5.2.8 on 2025-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_current_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='audience_reach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
