# Generated by Django 5.2.8 on 2025-12-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_influencerinfo_audience_reach_influencerinfo_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerinfo',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='linkedin_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='whatsapp_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='youtube_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
