# Generated by Django 5.2.9 on 2025-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_influencerinfo_instagram_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='rate_range_for_facebook_post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinfo',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
