# Generated by Django 5.2.9 on 2025-12-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_influencerinfo_facebook_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinfo',
            name='whatsapp_business',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
