# Generated by Django 5.2.9 on 2025-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_brandinfo_whatsapp_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='blog_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='facebook_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='insta_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='linkedin_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='tiktok_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='youtube_follower',
            field=models.IntegerField(default=0),
        ),
    ]
