# Generated by Django 5.2.9 on 2025-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_influencerinfo_blog_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
