# Generated by Django 5.2.9 on 2025-12-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_brandinfo_is_featured_influencerinfo_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='podcast_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='podcast_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='whatsapp_follower',
            field=models.IntegerField(default=0),
        ),
    ]
