# Generated by Django 5.2.9 on 2025-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_influencerinfo_podcast_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinfo',
            name='blog_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencerinfo',
            name='twitter_follower',
            field=models.IntegerField(default=0),
        ),
    ]
