# Generated by Django 5.2.9 on 2026-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_feedback_email_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='notifications_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='notifications_push',
            field=models.BooleanField(default=True),
        ),
    ]
