# Generated by Django 5.2.10 on 2026-01-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type_alias',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R'), ('O', 'O'), ('P', 'P'), ('O', 'O'), ('S', 'S'), ('A', 'A'), ('L', 'L'), ('_', '_'), ('S', 'S'), ('E', 'E'), ('N', 'N'), ('T', 'T'), ('P', 'P'), ('R', 'R'), ('O', 'O'), ('P', 'P'), ('O', 'O'), ('S', 'S'), ('A', 'A'), ('L', 'L'), ('_', '_'), ('A', 'A'), ('C', 'C'), ('C', 'C'), ('E', 'E'), ('P', 'P'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('P', 'P'), ('R', 'R'), ('O', 'O'), ('P', 'P'), ('O', 'O'), ('S', 'S'), ('A', 'A'), ('L', 'L'), ('_', '_'), ('R', 'R'), ('E', 'E'), ('J', 'J'), ('E', 'E'), ('C', 'C'), ('T', 'T'), ('E', 'E'), ('D', 'D'), ('F', 'F'), ('I', 'I'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('_', '_'), ('M', 'M'), ('E', 'E'), ('S', 'S'), ('S', 'S'), ('A', 'A'), ('G', 'G'), ('E', 'E'), ('N', 'N'), ('E', 'E'), ('W', 'W'), ('_', '_'), ('I', 'I'), ('N', 'N'), ('F', 'F'), ('L', 'L'), ('U', 'U'), ('E', 'E'), ('N', 'N'), ('C', 'C'), ('E', 'E'), ('R', 'R'), ('N', 'N'), ('E', 'E'), ('W', 'W'), ('_', '_'), ('B', 'B'), ('R', 'R'), ('A', 'A'), ('N', 'N'), ('D', 'D')], max_length=20, null=True),
        ),
    ]
