# Generated by Django 5.2.10 on 2026-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_log_type_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type_alias',
            field=models.CharField(choices=[('PROPOSAL_SENT', 'PROPOSAL_SENT'), ('PROPOSAL_ACCEPTED', 'PROPOSAL_ACCEPTED'), ('PROPOSAL_REJECTED', 'PROPOSAL_REJECTED'), ('FIRST_MESSAGE', 'FIRST_MESSAGE'), ('NEW_INFLUENCER', 'NEW_INFLUENCER'), ('NEW_BRAND', 'NEW_BRAND')], max_length=20, null=True),
        ),
    ]
