# Generated by Django 5.2.10 on 2026-01-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_log_type_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
