# Generated by Django 5.2.10 on 2026-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_userprofile_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_complete',
            new_name='is_brand_profile_complete',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_influencer_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
