# Generated by Django 5.2.11 on 2026-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rename_is_complete_userprofile_is_brand_profile_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinfo',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
