# Generated by Codex on 2026-03-29

from django.db import migrations, models


LOG_TYPE_ALIASES = (
    "PROPOSAL_SENT",
    "PROPOSAL_ACCEPTED",
    "PROPOSAL_REJECTED",
    "FIRST_MESSAGE",
    "NEW_INFLUENCER",
    "NEW_BRAND",
    "SUBSCRIPTION_CREATED",
    "SUBSCRIPTION_CANCELED",
    "CAMPAIGN_COMPLETED",
)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_savedinfluencer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="type_alias",
            field=models.CharField(
                choices=tuple(zip(LOG_TYPE_ALIASES, LOG_TYPE_ALIASES)),
                max_length=30,
                null=True,
            ),
        ),
    ]
