# Generated by Codex on 2026-03-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_alter_log_type_alias_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="influencerinfo",
            old_name="account_number",
            new_name="old_account_number",
        ),
        migrations.RenameField(
            model_name="influencerinfo",
            old_name="routing_number",
            new_name="old_routing_number",
        ),
        migrations.RenameField(
            model_name="influencerinfo",
            old_name="bank_name",
            new_name="old_bank_name",
        ),
        migrations.RenameField(
            model_name="influencerinfo",
            old_name="paypal_email",
            new_name="old_paypal_email",
        ),
    ]
