# Generated by Codex on 2026-03-30

from django.db import migrations

import authentication.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_rename_plaintext_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerinfo",
            name="account_number",
            field=authentication.fields.EncryptedCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="influencerinfo",
            name="routing_number",
            field=authentication.fields.EncryptedCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="influencerinfo",
            name="bank_name",
            field=authentication.fields.EncryptedCharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="influencerinfo",
            name="paypal_email",
            field=authentication.fields.EncryptedCharField(
                blank=True, max_length=100, null=True
            ),
        ),
    ]
