# Generated by Codex on 2026-03-30

from django.db import migrations


def forwards_copy_payment_fields(apps, schema_editor):
    InfluencerInfo = apps.get_model("authentication", "InfluencerInfo")

    for row in InfluencerInfo.objects.all().iterator():
        row.account_number = row.old_account_number
        row.routing_number = row.old_routing_number
        row.bank_name = row.old_bank_name
        row.paypal_email = row.old_paypal_email
        row.save(
            update_fields=[
                "account_number",
                "routing_number",
                "bank_name",
                "paypal_email",
            ]
        )


def reverse_copy_payment_fields(apps, schema_editor):
    InfluencerInfo = apps.get_model("authentication", "InfluencerInfo")

    for row in InfluencerInfo.objects.all().iterator():
        row.old_account_number = row.account_number
        row.old_routing_number = row.routing_number
        row.old_bank_name = row.bank_name
        row.old_paypal_email = row.paypal_email
        row.save(
            update_fields=[
                "old_account_number",
                "old_routing_number",
                "old_bank_name",
                "old_paypal_email",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_add_encrypted_payment_fields"),
    ]

    operations = [
        migrations.RunPython(forwards_copy_payment_fields, reverse_copy_payment_fields),
    ]
