# Generated by Codex on 2026-03-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_copy_payment_fields_to_encrypted_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="influencerinfo",
            name="old_account_number",
        ),
        migrations.RemoveField(
            model_name="influencerinfo",
            name="old_routing_number",
        ),
        migrations.RemoveField(
            model_name="influencerinfo",
            name="old_bank_name",
        ),
        migrations.RemoveField(
            model_name="influencerinfo",
            name="old_paypal_email",
        ),
    ]
