# Generated by Django 5.2.8 on 2025-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
