# Generated by Django 5.2.9 on 2025-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
