# Generated by Django 5.2.9 on 2025-12-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
