# Generated by Django 5.2.9 on 2025-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
