version: '3.8'

services:
  chat_service_lb:
    image: nginx:1.25-alpine
    container_name: chat_service_lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    networks:
      - microservices_shared_network
    depends_on:
      - chat_service

  chat_service:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 src.asgi:application
    volumes:
      - .:/app
    networks:
      - microservices_shared_network
    depends_on:
      - chat_postgres_db
    env_file:
      - .env

  chat_postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db_container_chat_service
    volumes:
      - chat_service_postgres_dataa:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=chat_service_db
      - POSTGRES_USER=chat_service_user
      - POSTGRES_PASSWORD=a_strong_password
    networks:
      - microservices_shared_network

networks:
  microservices_shared_network:
    external: true

volumes:
  chat_service_postgres_dataa: {}